from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(362, 559)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.Porcentagem = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("%"))
        self.Porcentagem.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.Porcentagem.setFont(font)
        self.Porcentagem.setObjectName("Porcentagem")
        self.limpar = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("C"))
        self.limpar.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.limpar.setFont(font)
        self.limpar.setObjectName("limpar")
        self.apagar = QtWidgets.QPushButton(Dialog, clicked = lambda: self.remover())
        self.apagar.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.apagar.setFont(font)
        self.apagar.setObjectName("apagar")
        self.dividir = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("/"))
        self.dividir.setGeometry(QtCore.QRect(275, 110, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.dividir.setFont(font)
        self.dividir.setObjectName("dividir")
        self.sete = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("7"))
        self.sete.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.sete.setFont(font)
        self.sete.setObjectName("sete")
        self.oito = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("8"))
        self.oito.setGeometry(QtCore.QRect(100, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.oito.setFont(font)
        self.oito.setObjectName("oito")
        self.nove = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("9"))
        self.nove.setGeometry(QtCore.QRect(190, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.nove.setFont(font)
        self.nove.setObjectName("nove")
        self.multiplicar = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("*"))
        self.multiplicar.setGeometry(QtCore.QRect(275, 200, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.multiplicar.setFont(font)
        self.multiplicar.setObjectName("multiplicar")
        self.subtrair = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("-"))
        self.subtrair.setGeometry(QtCore.QRect(275, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.subtrair.setFont(font)
        self.subtrair.setObjectName("subtrair")
        self.cinco = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("5"))
        self.cinco.setGeometry(QtCore.QRect(100, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.cinco.setFont(font)
        self.cinco.setObjectName("cinco")
        self.seis = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("6"))
        self.seis.setGeometry(QtCore.QRect(190, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.seis.setFont(font)
        self.seis.setObjectName("seis")
        self.quatro = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("4"))
        self.quatro.setGeometry(QtCore.QRect(10, 290, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.quatro.setFont(font)
        self.quatro.setObjectName("quatro")
        self.tres = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("3"))
        self.tres.setGeometry(QtCore.QRect(190, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.tres.setFont(font)
        self.tres.setObjectName("tres")
        self.somar = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("+"))
        self.somar.setGeometry(QtCore.QRect(275, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.somar.setFont(font)
        self.somar.setObjectName("somar")
        self.dois = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("2"))
        self.dois.setGeometry(QtCore.QRect(100, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.dois.setFont(font)
        self.dois.setObjectName("dois")
        self.um = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("1"))
        self.um.setGeometry(QtCore.QRect(10, 380, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.um.setFont(font)
        self.um.setObjectName("um")
        self.ponto = QtWidgets.QPushButton(Dialog, clicked = lambda: self.pontuar())
        self.ponto.setGeometry(QtCore.QRect(190, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.ponto.setFont(font)
        self.ponto.setObjectName("ponto")
        self.igual = QtWidgets.QPushButton(Dialog, clicked = lambda: self.calculo())
        self.igual.setGeometry(QtCore.QRect(275, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.igual.setFont(font)
        self.igual.setObjectName("igual")
        self.zero = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clique("0"))
        self.zero.setGeometry(QtCore.QRect(100, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.maismenos = QtWidgets.QPushButton(Dialog, clicked = lambda: self.maisoumenos())
        self.maismenos.setGeometry(QtCore.QRect(10, 470, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.maismenos.setFont(font)
        self.maismenos.setObjectName("maismenos")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    #calculo matemático
    def calculo(self):
        # manter o valor que já está na tela
        tela = self.label.text()
        try:
            #Trazer o resultado usando a função eval, ela lê a função, identifica a operação e traz o resultado
            resposta = eval(tela)
            self.label.setText(str(resposta))
        except:
            self.label.setText("Error")

    #colocar o sinal de menos no valor - Arrumar o replace
    def maisoumenos(self):
        # manter o valor que já está na tela
        tela = self.label.text()
        if tela.startswith("-"):
            x = tela.find("-")+1
            self.label.setText(tela.replace("-","",x))
        else:
            self.label.setText(f'-{tela}')

    def remover(self):
        #manter o valor que já está na tela
        tela = self.label.text()
        #remove o último valor da tela
        tela = tela[:-1]
        #resultado da variavel tela
        self.label.setText(tela)

    def pontuar(self):
        tela = self.label.text()
        if tela[-1] == ".":
            pass
        elif tela.__contains__("."):
            pass
        else:
            self.label.setText(f'{tela}.')
    #Inserir valores na calculadora
    def clique(self,click):
        #limpar o label
        if click == "C":
            self.label.setText("0")
        else:
            #substituir o zero inicial por vazio
            if self.label.text() == "0":
                self.label.setText("")
                self.label.setText(f'{click}')
            else:
                #Concatenar valores preechidos
                self.label.setText(f'{self.label.text()}{click}')

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialoag", "Dialog"))
        self.label.setText(_translate("Dialog", "0"))
        self.Porcentagem.setText(_translate("Dialog", "%"))
        self.limpar.setText(_translate("Dialog", "C"))
        self.apagar.setText(_translate("Dialog", "<<"))
        self.dividir.setText(_translate("Dialog", "/"))
        self.sete.setText(_translate("Dialog", "7"))
        self.oito.setText(_translate("Dialog", "8"))
        self.nove.setText(_translate("Dialog", "9"))
        self.multiplicar.setText(_translate("Dialog", "X"))
        self.subtrair.setText(_translate("Dialog", "-"))
        self.cinco.setText(_translate("Dialog", "5"))
        self.seis.setText(_translate("Dialog", "6"))
        self.quatro.setText(_translate("Dialog", "4"))
        self.tres.setText(_translate("Dialog", "3"))
        self.somar.setText(_translate("Dialog", "+"))
        self.dois.setText(_translate("Dialog", "2"))
        self.um.setText(_translate("Dialog", "1"))
        self.ponto.setText(_translate("Dialog", "."))
        self.igual.setText(_translate("Dialog", "="))
        self.zero.setText(_translate("Dialog", "0"))
        self.maismenos.setText(_translate("Dialog", "+/-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())